# Site wide configuration

title:            Developer de Pueblo
locale:           es_ES
url:              http://www.developerdepueblo.com
#url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Jose Ignacio Andrés
  avatar: bio-photo.jpg
  bio: "Trabajo como CTO & developer en <a href='https://twitter.com/dokify'>@dokify</a>, soy de <a href='https://www.google.es/maps/place/37521+Robleda,+Salamanca/@40.3518378,-6.6052238,3987a,20y,40.83t/data=!3m1!1e3!4m2!3m1!1s0xd3dcdc761c96a6f:0x490862031a1db018' target='_blank'>Robleda</a> y trato de aprender algo nuevo cada día."
  email: joseignacio.andres.h@gmail.com
  disqus-shortname:
  twitter: joserobleda
  facebook: #username
  google:
    plus: JoseIgnacioAndres
    analytics: UA-54327363-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: joserobleda
  stackoverflow: http://stackoverflow.com/users/1811887/joserobleda
  linkedin: jose-ignacio-andres
  instagram: joserobleda
  lastfm: joserobleda
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
